name: SwipeTypeMac
options:
  bundleIdPrefix: com.swipetype
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    PRODUCT_NAME: SwipeType
    MARKETING_VERSION: "0.1.2"
    CURRENT_PROJECT_VERSION: "7"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    ENABLE_HARDENED_RUNTIME: YES
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""

targets:
  SwipeTypeMac:
    type: application
    platform: macOS
    sources:
      - path: Sources/SwipeTypeMac
        excludes:
          - "**/.DS_Store"
      - path: Sources/SwipeTypeMac/Engine/SwipeEngine.h
        buildPhase: headers
      - path: ../../word_freq.txt
        buildPhase: resources
    settings:
      base:
        INFOPLIST_FILE: Support/Info.plist
        CODE_SIGN_ENTITLEMENTS: Support/SwipeTypeMac.entitlements
        SWIFT_OBJC_BRIDGING_HEADER: Sources/SwipeTypeMac/Engine/SwipeEngine.h
        LIBRARY_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Rust"
        OTHER_LDFLAGS:
          - "-lswipe_engine"
          - "-framework Security"
          - "-framework Carbon"
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
    dependencies: []
